/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package com.epiis.app.presentation;

import com.epiis.app.presentation.person.FrmPersonGetAll;
import com.epiis.app.presentation.person.FrmPersonInsert;
import javax.swing.JFrame;

/**
 *
 * @author KAAF0
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        personMenu = new javax.swing.JMenu();
        personInsertMenuItem = new javax.swing.JMenuItem();
        personGetAllMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        fileMenu.setText("Archivo");

        exitMenuItem.setText("Salir");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        personMenu.setText("Mantenimiento de persona");

        personInsertMenuItem.setText("Registrar");
        personInsertMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personInsertMenuItemActionPerformed(evt);
            }
        });
        personMenu.add(personInsertMenuItem);

        personGetAllMenuItem.setText("Listar");
        personGetAllMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personGetAllMenuItemActionPerformed(evt);
            }
        });
        personMenu.add(personGetAllMenuItem);

        menuBar.add(personMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void personInsertMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personInsertMenuItemActionPerformed
        FrmPersonInsert frmPersonInsert = new FrmPersonInsert();
        
        this.desktopPane.add(frmPersonInsert);
        
        frmPersonInsert.setVisible(true);
    }//GEN-LAST:event_personInsertMenuItemActionPerformed

    private void personGetAllMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personGetAllMenuItemActionPerformed
        FrmPersonGetAll frmPersonGetAll = new FrmPersonGetAll();
        
        this.desktopPane.add(frmPersonGetAll);
        
        frmPersonGetAll.setVisible(true);
    }//GEN-LAST:event_personGetAllMenuItemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem personGetAllMenuItem;
    private javax.swing.JMenuItem personInsertMenuItem;
    private javax.swing.JMenu personMenu;
    // End of variables declaration//GEN-END:variables

}
